name: UpdateWeChatWin

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      download_link:
        description: 'The manual WeChatWin.exe download link'
        required: false
        default: 'https://dldir1v6.qq.com/weixin/Universal/Windows/WeChatWin.exe'

jobs:
  check_new_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check new version and push
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bash -x ./releaseWeChatWin.sh ${{ github.event.inputs.download_link }}
